if CLIENT then
    --添加菜单
    hook.Add( "AddToolMenuCategories", "RealismGunSwayCategory", function()
        spawnmenu.AddToolCategory( "Utilities", "Realism Gun Sway Menu", "Realism Gun Sway Menu" )
    end )
    hook.Add("PopulateToolMenu", "RealismGunSwayMenu", function()
        if(GetConVar("gmod_language"):GetString() == "zh-CN") then
            spawnmenu.AddToolMenuOption("Utilities", "Realism Gun Sway Menu", "Realism_Gun_Sway_Menu", "Realism Gun Sway Menu", "", "", function(panel)
                panel:ClearControls()
                panel:Help("------------------现实主义枪摆------------------")
                panel:CheckBox( "启用", 'cl_realismGunSway_enabled' )
                panel:NumSlider( "浮动速度", "cl_realismGunSway_flSpeed", 1, 20,0)
                panel:NumSlider( "浮动范围", "cl_realismGunSway_maxflScale", 1, 30,0)
                panel:NumSlider( "浮动灵敏度", "cl_realismGunSway_flSensitivity", 0.1, 1,1)
                panel:CheckBox( "仅瞄准时随动", 'cl_realismGunSway_onlyAimFl' )
                panel:Help("是否开启仅瞄准时随动,建议开启（适配mwbase,tfa,arccw,arc9）")
                panel:CheckBox( "反向浮动", 'cl_realismGunSway_reverse' )
                panel:Help("------------------移动时的随动------------------")
                panel:CheckBox( "开启移动时的随动", 'My_WalkViewModelLerp_enable' )
                panel:NumSlider( "浮动比例", "My_WalkViewModelLerp_Rate", 0.1, 10,1)
                panel:NumSlider( "浮动速度", "My_WalkViewModelLerp_speed", 1, 10,1)
                panel:Help("------------------瞄准死区------------------")
                panel:Help("目前仅有mwbase,arc9,tfa适配")
                panel:CheckBox( "开启瞄准死区", 'cl_realismGunSway_aimDeadZone' )
                panel:CheckBox( "viewModel不返回中心", 'cl_realismGunSway_shouldNotReturn' )
                panel:NumSlider( "死区灵敏度 x", "cl_realismGunSway_deadZoneSensitivity_X", 0.2, 5,1)
                panel:NumSlider( "死区灵敏度 y", "cl_realismGunSway_deadZoneSensitivity_Y", 0.2, 5,1)
                panel:NumSlider( "死区角度对齐", "cl_realismGunSway_deadZoneAngDiff", 0, 1,1)
                panel:Help("死区角度对齐: 当参数越小时，武器偏转角度越与视角保持一致")
                panel:Help("")
                panel:NumSlider( "强制弹道修正", "cl_realismGunSway_forceTrajector", 0.01, 5,2)
                panel:Help("(默认 1.00)")
                panel:Help("用于手动校准武器弹道，通常来说你不需要手动调整，但对部分arc9武器来说，调整该值能让你的瞄具准心与弹着点一致")
                panel:Help("请谨慎调整该参数")
                local btnReset = panel:Button("恢复默认值")
                btnReset:SetSize( 100, 50 )
                btnReset.DoClick = function()
                    LocalPlayer():ConCommand("cl_realismGunSway_flSpeed 7")
                    LocalPlayer():ConCommand("cl_realismGunSway_maxflScale 4")
                    LocalPlayer():ConCommand("cl_realismGunSway_flSensitivity 0.2")
                    LocalPlayer():ConCommand("cl_realismGunSway_onlyAimFl 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_reverse 0")
                    LocalPlayer():ConCommand("cl_realismGunSway_aimDeadZone 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_shouldNotReturn 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneAngDiff 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneSensitivity_X 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneSensitivity_Y 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_forceTrajector 1.0")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_enable 1")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_Rate 1.5")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_speed 2.5")
                end
            end)

            spawnmenu.AddToolMenuOption("Utilities", "Realism Gun Sway Menu", "Realism_Gun_Ready_Menu", "Realism Gun Ready", "", "", function(panel)
                panel:ClearControls()
                panel:Help("------------------战术姿态------------------")
                panel:CheckBox( "启用", 'cl_realismGunReady_enabled' )
                panel:AddControl("Numpad", {
                    Label = "Bind key",
                    Command = "cl_realismGunReady_bindkey"
                })
                panel:Help("战术姿态绑定键，按下这个按键并滑动鼠标滚轮以切换战术姿态")
            end)
        else
            spawnmenu.AddToolMenuOption("Utilities", "Realism Gun Sway Menu", "Realism_Gun_Sway_Menu", "Realism Gun Sway Menu", "", "", function(panel)
                panel:ClearControls()
                panel:Help("------------------Realism Gun Sway------------------")
                panel:CheckBox( "Enable", 'cl_realismGunSway_enabled' )
                panel:Help("Enable or Disable Realism Gun Sway")
                panel:NumSlider( "float Speed", "cl_realismGunSway_flSpeed", 1, 20,0)
                panel:Help("Influence the float speed")
                panel:NumSlider( "float Scale", "cl_realismGunSway_maxflScale", 1, 30,0)
                panel:Help("Influence the float scale")
                panel:NumSlider( "float sensitivity", "cl_realismGunSway_flSensitivity", 0.1, 1,1)
                panel:Help("Influence the float sensitivity")
                panel:CheckBox( "Only Aim Float", 'cl_realismGunSway_onlyAimFl' )
                panel:Help("Do you want to enable lagger only when aiming? (suitable for mwbase,tfa,arccw,arc9)")
                panel:CheckBox( "direction reverse", 'cl_realismGunSway_reverse' )
                panel:Help("Get lagger in reverse direction")
                panel:Help("------------------Movement sway------------------")
                panel:CheckBox( "Enable Movement sway", 'My_WalkViewModelLerp_enable' )
                panel:NumSlider( "Movement Lerp Rate", "My_WalkViewModelLerp_Rate", 0.1, 10,1)
                panel:NumSlider( "Movement Lerp speed", "My_WalkViewModelLerp_speed", 1, 10,1)
                panel:Help("------------------aim DeadZone------------------")
                panel:Help("Only work with mwbase, arc9, tfa")
                panel:CheckBox( "Enable DeadZone", 'cl_realismGunSway_aimDeadZone' )
                panel:Help("Should viewModel return to your screen center?")
                panel:CheckBox( "Not Return", 'cl_realismGunSway_shouldNotReturn' )
                panel:NumSlider( "DeadZone sensitivity x", "cl_realismGunSway_deadZoneSensitivity_X", 0.2, 5,1)
                panel:NumSlider( "DeadZone sensitivity y", "cl_realismGunSway_deadZoneSensitivity_Y", 0.2, 5,1)
                panel:NumSlider( "DeadZone angle align", "cl_realismGunSway_deadZoneAngDiff", 0, 1,1)
                panel:Help("DeadZone angle align: The smaller the value, the more aligned angle")
                panel:Help("")
                panel:NumSlider( "Ballistic force alignment", "cl_realismGunSway_forceTrajector", 0.01, 5,2)
                panel:Help("(default 1.00)")
                panel:Help("Used to manually adjust trajector,Usually you don't need to make adjustments")
                panel:Help("You must adjust this value very carefully")
                local btnReset = panel:Button("Set to my recommand value")
                btnReset:SetSize( 100, 50 )
                btnReset.DoClick = function()
                    LocalPlayer():ConCommand("cl_realismGunSway_flSpeed 7")
                    LocalPlayer():ConCommand("cl_realismGunSway_maxflScale 4")
                    LocalPlayer():ConCommand("cl_realismGunSway_flSensitivity 0.2")
                    LocalPlayer():ConCommand("cl_realismGunSway_onlyAimFl 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_reverse 0")
                    LocalPlayer():ConCommand("cl_realismGunSway_aimDeadZone 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_shouldNotReturn 1")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneAngDiff 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneSensitivity_X 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_deadZoneSensitivity_Y 1.0")
                    LocalPlayer():ConCommand("cl_realismGunSway_forceTrajector 1.0")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_enable 1")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_Rate 1.5")
                    LocalPlayer():ConCommand("My_WalkViewModelLerp_speed 2.5")
                end
            end)
            spawnmenu.AddToolMenuOption("Utilities", "Realism Gun Sway Menu", "Realism_Gun_Ready_Menu", "Realism Gun Ready", "", "", function(panel)
                panel:ClearControls()
                panel:Help("------------------Tactical Gun Ready------------------")
                panel:CheckBox( "Enable", 'cl_realismGunReady_enabled' )
                panel:AddControl("Numpad", {
                    Label = "Bind key",
                    Command = "cl_realismGunReady_bindkey"
                })
                panel:Help("Tactical Gun Ready bind, press this button and slide the mouseWheel to switch")
            end)
        end
    end)
end