GProfiler.Language = GProfiler.Language or {}
GProfiler.Language.Langs = GProfiler.Language.Langs or {}

function GProfiler.Language:AddLanguage(lang, cb)
	GProfiler.Language.Langs[lang] = {}

	local LangGroup = {}

	function LangGroup:AddPhrase(key, phrase)
		self[key] = phrase
	end

	function LangGroup:Save()
		GProfiler.Language.Langs[lang] = self
	end

	cb(LangGroup)
end

function GProfiler.Language.GetPhrase(key)
	local Lang = GProfiler.Language.Langs[GProfiler.Config.Language]
	if not Lang then Lang = GProfiler.Language.Langs["english"] end

	return Lang[key] or (GProfiler.Config.Language ~= "english" and GProfiler.Language.Langs["english"][key] or key) or key
end

GProfiler.Language:AddLanguage("english", function(Lang)
	-- General
	Lang:AddPhrase("uptime", "Uptime: %s")
	Lang:AddPhrase("profiler_results", "Profiler Results")
	Lang:AddPhrase("profiler_start", "Start Profiling")
	Lang:AddPhrase("profiler_stop", "Stop Profiling")
	Lang:AddPhrase("realm_client", "Client")
	Lang:AddPhrase("realm_server", "Server")
	Lang:AddPhrase("copy", "Copy")

	-- Column Names
	Lang:AddPhrase("file", "File")
	Lang:AddPhrase("name", "Name")
	Lang:AddPhrase("type", "Type")
	Lang:AddPhrase("lines", "Lines")
	Lang:AddPhrase("realm", "Realm")
	Lang:AddPhrase("focus", "Focus")
	Lang:AddPhrase("remove", "Remove")
	Lang:AddPhrase("function", "Function")
	Lang:AddPhrase("receivers", "Receivers")
	Lang:AddPhrase("receiver", "Receiver")
	Lang:AddPhrase("total_time", "Total Time")
	Lang:AddPhrase("times_called", "Times Called")
	Lang:AddPhrase("times_run", "Times Run")
	Lang:AddPhrase("times_received", "Times Received")
	Lang:AddPhrase("largest_size", "Largest Size")
	Lang:AddPhrase("total_size", "Total Size")
	Lang:AddPhrase("delay", "Delay")
	Lang:AddPhrase("timer", "Timer")
	Lang:AddPhrase("command", "Command")
	Lang:AddPhrase("average_time", "Average Time")
	Lang:AddPhrase("longest_time", "Longest Time")
	Lang:AddPhrase("entity", "Entity")
	Lang:AddPhrase("variable", "Variable")
	Lang:AddPhrase("times_updated", "Times Updated")
	Lang:AddPhrase("current_value", "Current Value")

	-- Profiler Specific
	Lang:AddPhrase("timer_function", "Timer Function")
	Lang:AddPhrase("timer_select", "Select a timer to view its code")
	Lang:AddPhrase("function_details", "Function Details")
	Lang:AddPhrase("function_select", "Select a function to view its code")
	Lang:AddPhrase("command_function", "Command Function")
	Lang:AddPhrase("command_select", "Select a command to view its code")
	Lang:AddPhrase("print_details", "Print Details")
	Lang:AddPhrase("printed", "Printed to Console")
	Lang:AddPhrase("requesting_source", "Requesting source from server...")
	Lang:AddPhrase("hook_select", "Select a hook to view its code")
	Lang:AddPhrase("receiver_select", "Select a receiver to view its code")

	-- Tab Names
	Lang:AddPhrase("tab_hooks", "Hooks")
	Lang:AddPhrase("tab_networking", "Networking")
	Lang:AddPhrase("tab_functions", "Functions")
	Lang:AddPhrase("tab_commands", "Commands")
	Lang:AddPhrase("tab_timers", "Timers")
	Lang:AddPhrase("tab_entity_variables", "Entity Variables")
	Lang:AddPhrase("tab_network_variables", "Network Variables")

	Lang:Save()
end)

GProfiler.Language:AddLanguage("french", function(Lang)
	-- General
	Lang:AddPhrase("uptime", "Temps en ligne: %s")
	Lang:AddPhrase("profiler_results", "Résultat du Profiler")
	Lang:AddPhrase("profiler_start", "Commencer le profilage")
	Lang:AddPhrase("profiler_stop", "Terminer le profilage")
	Lang:AddPhrase("realm_client", "Client")
	Lang:AddPhrase("realm_server", "Serveur")
	Lang:AddPhrase("copy", "Copier")

	-- Column Names
	Lang:AddPhrase("file", "Fichier")
	Lang:AddPhrase("name", "Noms")
	Lang:AddPhrase("type", "Type")
	Lang:AddPhrase("lines", "Lignes")
	Lang:AddPhrase("realm", "Realm")
	Lang:AddPhrase("focus", "Focus")
	Lang:AddPhrase("remove", "Supprimer")
	Lang:AddPhrase("function", "Fonction")
	Lang:AddPhrase("receivers", "Receveurs")
	Lang:AddPhrase("receiver", "Receveur")
	Lang:AddPhrase("total_time", "Temps total")
	Lang:AddPhrase("times_called", "Horaires appelés")
	Lang:AddPhrase("times_run", "Horaires Exécuté")
	Lang:AddPhrase("times_received", "Horaires Recu")
	Lang:AddPhrase("largest_size", "Tailles le plus large")
	Lang:AddPhrase("total_size", "Taille Total")
	Lang:AddPhrase("delay", "Delaie")
	Lang:AddPhrase("timer", "Minuterie")
	Lang:AddPhrase("command", "Commande")
	Lang:AddPhrase("average_time", "Temps Moyen")
	Lang:AddPhrase("longest_time", "Temps le plus long")
	Lang:AddPhrase("entity", "Entité")
	Lang:AddPhrase("variable", "Variable")
	Lang:AddPhrase("times_updated", "Horaires mis à jour")
	Lang:AddPhrase("current_value", "Valeur Actuelle")

	-- Profiler Specific
	Lang:AddPhrase("timer_function", "Fonctions Minuteries")
	Lang:AddPhrase("timer_select", "Selectionnez une Minuterie pour voir sa fonction")
	Lang:AddPhrase("function_details", "Détails de la Fonction")
	Lang:AddPhrase("function_select", "Selectionne une fonction pour voir sa minuterie")
	Lang:AddPhrase("command_function", "Fonction de commande")
	Lang:AddPhrase("command_select", "Selectionnez une fonction pour voir sa commande")
	Lang:AddPhrase("print_details", "Imprimer les details")
	Lang:AddPhrase("printed", "Imprimé dans la console (F10)")
	Lang:AddPhrase("requesting_source", "Demande de source au serveur...")
	Lang:AddPhrase("hook_select", "Selectionnez un hook pour voir sa fonction")
	Lang:AddPhrase("receiver_select", "Selectionnez un receveur pour voir sa fonction")

	-- Tab Names
	Lang:AddPhrase("tab_hooks", "HOOKS")
	Lang:AddPhrase("tab_networking", "Réseau")
	Lang:AddPhrase("tab_functions", "Fonctions")
	Lang:AddPhrase("tab_commands", "Commandes")
	Lang:AddPhrase("tab_timers", "Minuteries")
	Lang:AddPhrase("tab_entity_variables", "Variables des Entités")
	Lang:AddPhrase("tab_network_variables", "Variables du Réseau")

	Lang:Save()
end)

GProfiler.Language:AddLanguage("german", function(Lang)
	-- General
	Lang:AddPhrase("uptime", "Server-Laufzeit: %s")
	Lang:AddPhrase("profiler_results", "Profiler-Ergebnisse")
	Lang:AddPhrase("profiler_start", "Profiler starten")
	Lang:AddPhrase("profiler_stop", "Profiler stoppen")
	Lang:AddPhrase("realm_client", "Klient")
	Lang:AddPhrase("realm_server", "Server")
	Lang:AddPhrase("copy", "Kopieren")

	-- Column Names
	Lang:AddPhrase("file", "Dateipfad")
	Lang:AddPhrase("name", "Name")
	Lang:AddPhrase("type", "Typ")
	Lang:AddPhrase("lines", "Zeilen")
	Lang:AddPhrase("realm", "Umgebung")
	Lang:AddPhrase("focus", "Fokus")
	Lang:AddPhrase("remove", "Entfernen")
	Lang:AddPhrase("function", "Funktion")
	Lang:AddPhrase("receivers", "Empfänger")
	Lang:AddPhrase("receiver", "Empfänger")
	Lang:AddPhrase("total_time", "Aggregierte Dauer")
	Lang:AddPhrase("times_called", "Aufrufe")
	Lang:AddPhrase("times_run", "Aufrufe")
	Lang:AddPhrase("times_received", "Erhalten")
	Lang:AddPhrase("largest_size", "Maximale Größe")
	Lang:AddPhrase("total_size", "Aggregierte Größe")
	Lang:AddPhrase("delay", "Intervall")
	Lang:AddPhrase("timer", "Timer")
	Lang:AddPhrase("command", "Befehl")
	Lang:AddPhrase("average_time", "Durchschnittliche Dauer")
	Lang:AddPhrase("longest_time", "Längste Dauer")
	Lang:AddPhrase("entity", "Entität")
	Lang:AddPhrase("variable", "Variable")
	Lang:AddPhrase("times_updated", "Änderungen")
	Lang:AddPhrase("current_value", "Aktueller Wert")

	-- Profiler Specific
	Lang:AddPhrase("timer_function", "Quellcode des Timers")
	Lang:AddPhrase("timer_select", "Wähle einen Timer, zu dem du den Quellcode sehen willst.")
	Lang:AddPhrase("function_details", "Quellcode der Funktion")
	Lang:AddPhrase("function_select", "Wähle eine Funktion, zu der du den Quellcode sehen willst.")
	Lang:AddPhrase("command_function", "Quellcode des Befehls")
	Lang:AddPhrase("command_select", "Wähle einen Befehl, zu dem du den Quellcode sehen willst.")
	Lang:AddPhrase("print_details", "Details ausgeben")
	Lang:AddPhrase("printed", "Details wurden in der Konsole ausgegeben!")
	Lang:AddPhrase("requesting_source", "Quellcode wird abgefragt...")
	Lang:AddPhrase("hook_select", "Wähle einen Hook, zu dem du den Quellcode sehen willst.")
	Lang:AddPhrase("receiver_select", "Wähle einen Empfänger, zu dem du den Quellcode sehen willst.")

	-- Tab Names
	Lang:AddPhrase("tab_hooks", "Hooks")
	Lang:AddPhrase("tab_networking", "Netzwerk")
	Lang:AddPhrase("tab_functions", "Funktionen")
	Lang:AddPhrase("tab_commands", "Befehle")
	Lang:AddPhrase("tab_timers", "Timer")
	Lang:AddPhrase("tab_entity_variables", "Entitätsvariablen")
	Lang:AddPhrase("tab_network_variables", "Netzwerkvariablen")

	Lang:Save()
end)

GProfiler.Language:AddLanguage("dutch", function(Lang)
	-- General
	Lang:AddPhrase("uptime", "Uptime: %s")
	Lang:AddPhrase("profiler_results", "Profiler Resultaten")
	Lang:AddPhrase("profiler_start", "Start Profiling")
	Lang:AddPhrase("profiler_stop", "Stop Profiling")
	Lang:AddPhrase("realm_client", "Client")
	Lang:AddPhrase("realm_server", "Server")
	Lang:AddPhrase("copy", "KopiÃ«ren")

	-- Column Names
	Lang:AddPhrase("file", "Document")
	Lang:AddPhrase("name", "Naam")
	Lang:AddPhrase("type", "Type")
	Lang:AddPhrase("lines", "Lijnen")
	Lang:AddPhrase("realm", "Realm")
	Lang:AddPhrase("focus", "Focus")
	Lang:AddPhrase("remove", "Verwijderen")
	Lang:AddPhrase("function", "Functie")
	Lang:AddPhrase("receivers", "Ontvangers")
	Lang:AddPhrase("receiver", "Ontvanger")
	Lang:AddPhrase("total_time", "Totale tijd")
	Lang:AddPhrase("times_called", "Aantal Keer Opgeroepen")
	Lang:AddPhrase("times_run", "Aantal Keer Gerunt")
	Lang:AddPhrase("times_received", "Aantal Keer Ontvangen")
	Lang:AddPhrase("largest_size", "Grootste Formaat")
	Lang:AddPhrase("total_size", "Totale Grote")
	Lang:AddPhrase("delay", "Delay")
	Lang:AddPhrase("timer", "Timer")
	Lang:AddPhrase("command", "Command")
	Lang:AddPhrase("average_time", "Gemiddelde Tijd")
	Lang:AddPhrase("longest_time", "Langste Tijd")
	Lang:AddPhrase("entity", "Entiteit")
	Lang:AddPhrase("variable", "Variabelen")
	Lang:AddPhrase("times_updated", "Aantal Keer Geupdate")
	Lang:AddPhrase("current_value", "Huidige Waarde")

	-- Profiler Specific
	Lang:AddPhrase("timer_function", "Timer Functie")
	Lang:AddPhrase("timer_select", "Selecteer een timer om de code te bekijken")
	Lang:AddPhrase("function_details", "Functie Details")
	Lang:AddPhrase("function_select", "Selecteer een functie om de code te bekijken")
	Lang:AddPhrase("command_function", "Command Functie")
	Lang:AddPhrase("command_select", "Selecteer een command om de code te bekijken")
	Lang:AddPhrase("print_details", "Afdruk Details")
	Lang:AddPhrase("printed", "Afgedrukt Naar Console")
	Lang:AddPhrase("requesting_source", "Bron opvragen bij server...")
	Lang:AddPhrase("hook_select", "Selecteer een hook om de code te bekijken")
	Lang:AddPhrase("receiver_select", "Selecteer een ontvanger om de code te bekijken")

	-- Tab Names
	Lang:AddPhrase("tab_hooks", "Hooks")
	Lang:AddPhrase("tab_networking", "Networking")
	Lang:AddPhrase("tab_functions", "Functies")
	Lang:AddPhrase("tab_commands", "Commands")
	Lang:AddPhrase("tab_timers", "Timers")
	Lang:AddPhrase("tab_entity_variables", "Entiteit Variabelen")
	Lang:AddPhrase("tab_network_variables", "Network Variabelen")

	Lang:Save()
end)

GProfiler.Language:AddLanguage("russian", function(Lang)
	-- General
	Lang:AddPhrase("uptime", "Время работы: %s")
	Lang:AddPhrase("profiler_results", "Результаты профилирования")
	Lang:AddPhrase("profiler_start", "Начать профилирование")
	Lang:AddPhrase("profiler_stop", "Остановить профилирование")
	Lang:AddPhrase("realm_client", "Клиент")
	Lang:AddPhrase("realm_server", "Сервер")
	Lang:AddPhrase("copy", "Копировать")

	-- Column Names
	Lang:AddPhrase("file", "Файл")
	Lang:AddPhrase("name", "Имя")
	Lang:AddPhrase("type", "Тип")
	Lang:AddPhrase("lines", "Строки")
	Lang:AddPhrase("realm", "Область")
	Lang:AddPhrase("focus", "Фокус")
	Lang:AddPhrase("remove", "Удалить")
	Lang:AddPhrase("function", "Функция")
	Lang:AddPhrase("receivers", "Получатели")
	Lang:AddPhrase("receiver", "Получатель")
	Lang:AddPhrase("total_time", "Общее время")
	Lang:AddPhrase("times_called", "Время вызова")
	Lang:AddPhrase("times_run", "Время работы")
	Lang:AddPhrase("times_received", "Время получения")
	Lang:AddPhrase("largest_size", "Наибольший размер")
	Lang:AddPhrase("total_size", "Общий размер")
	Lang:AddPhrase("delay", "Задержка")
	Lang:AddPhrase("timer", "Таймер")
	Lang:AddPhrase("command", "Команда")
	Lang:AddPhrase("average_time", "Среднее время")
	Lang:AddPhrase("longest_time", "Самое продолжительное время")
	Lang:AddPhrase("entity", "Сущность")
	Lang:AddPhrase("variable", "Переменная")
	Lang:AddPhrase("times_updated", "Время обновления")
	Lang:AddPhrase("current_value", "Текущее значение")

	-- Profiler Specific
	Lang:AddPhrase("timer_function", "Функция таймера")
	Lang:AddPhrase("timer_select", "Выберите таймер для просмотра его кода")
	Lang:AddPhrase("function_details", "Детали функции")
	Lang:AddPhrase("function_select", "Выберите функцию для просмотра ее кода")
	Lang:AddPhrase("command_function", "Командная функция")
	Lang:AddPhrase("command_select", "Выберите команду для просмотра ее кода")
	Lang:AddPhrase("print_details", "Подробные сведения о печати")
	Lang:AddPhrase("printed", "Напечатано в консоли")
	Lang:AddPhrase("requesting_source", "Запрос исходного кода с сервера...")
	Lang:AddPhrase("hook_select", "Выберите хук для просмотра его кода")
	Lang:AddPhrase("receiver_select", "Выберите получателя для просмотра его кода")

	-- Tab Names
	Lang:AddPhrase("tab_hooks", "Хуки")
	Lang:AddPhrase("tab_networking", "Сетевые параметры")
	Lang:AddPhrase("tab_functions", "Функции")
	Lang:AddPhrase("tab_commands", "Команды")
	Lang:AddPhrase("tab_timers", "Таймеры")
	Lang:AddPhrase("tab_entity_variables", "Переменные сущности")
	Lang:AddPhrase("tab_network_variables", "Сетевые переменные")

	Lang:Save()
end)