CreateConVar("physfiz_enabled", "1", FCVAR_ARCHIVE + FCVAR_REPLICATED + FCVAR_NOTIFY, "Whether fizzling will be enabled at all.", 0, 1)
CreateConVar("sv_physfiz_unjam", "0", {FCVAR_ARCHIVE, FCVAR_REPLICATED}, "Whether you can mash keys to unjam the physgun quicker.", 0, 1)
if SERVER then
    CreateConVar("sv_physfiz_chance_playerhit", "0.8", FCVAR_ARCHIVE, "The chance of fizzling when the player is shot.", 0, 1)
    CreateConVar("sv_physfiz_chance_prophit", "0.5", FCVAR_ARCHIVE, "The chance of fizzling when the prop held by the player is shot.", 0, 1)
    CreateConVar("sv_physfiz_chance_damagethreshold", "10", FCVAR_ARCHIVE, "The minimum damage below which the chance of fizzling is reduced.", 0)
    CreateConVar("sv_physfiz_chance_damagethreshold_linear", "1", FCVAR_ARCHIVE, "Whether to linearly reduce chance when damage is low. If set to 0, damage below threshold will have no chance.", 0, 1)
    CreateConVar("sv_physfiz_timemin", "7", FCVAR_ARCHIVE, "Minimum amount of time to disable the physgun.", 0)
    CreateConVar("sv_physfiz_timemax", "10", FCVAR_ARCHIVE, "Maximum amount of time to disable the physgun.", 0)
    CreateConVar("sv_physfiz_pvponly", "0", FCVAR_ARCHIVE, "Whether only player damage will cause fizzling.", 0, 1)
    CreateConVar("sv_physfiz_blockprop", "1", FCVAR_ARCHIVE, "Whether fizzling also blocks prop spawning.", 0, 1)
    
    CreateConVar("sv_physfiz_unjam_amount", "0.1", FCVAR_ARCHIVE, "The amount of fizzle time to reduce per button press.", 0)
elseif CLIENT then
    CreateConVar("cl_physfiz_sounds", "1", FCVAR_ARCHIVE, "Whether to enable spark sounds.", 0, 1)
    CreateConVar("cl_physfiz_whiteflash", "1", FCVAR_ARCHIVE, "Whether to force other players' disable flash be white (weapon color can be hard to see).", 0, 1)

    local function options(cpanel)
        cpanel:AddControl("Header", {Description = "Client"})
        cpanel:AddControl("Checkbox", {Label = "Enable Spark Sounds?", Command = "cl_physfiz_sounds" })
        cpanel:AddControl("Checkbox", {Label = "Force white flash?", Command = "cl_physfiz_whiteflash" })
        cpanel:AddControl("Header", {Description = ""})
        cpanel:AddControl("Header", {Description = "Server"})
        cpanel:AddControl("Checkbox", {Label = "Enable all features?", Command = "physfiz_enabled" })
        cpanel:AddControl("Slider", {Label = "Chance on player hit", Command = "sv_physfiz_chance_playerhit", Min = 0, Max = 1, Type = "float" })
        cpanel:AddControl("Slider", {Label = "Chance on prop hit", Command = "sv_physfiz_chance_prophit", Min = 0, Max = 1, Type = "float" })
        cpanel:AddControl("Slider", {Label = "Damage threshold", Command = "sv_physfiz_chance_prophit", Min = 0, Max = 100, Type = "int" })
        cpanel:AddControl("Checkbox", {Label = "Linear chance reduction?", Command = "sv_physfiz_chance_damagethreshold_linear" })
        cpanel:AddControl("Label", {Text = "If linear reduction is set, damage below the threshold have a linearly reduced chance of causing fizzle. Otherwise, damage below the threshold won't cause fizzling at all." })
        cpanel:AddControl("Slider", {Label = "Minimum disable time", Command = "sv_physfiz_timemin", Min = 1, Max = 60, Type = "float" })
        cpanel:AddControl("Slider", {Label = "Maximum disable time", Command = "sv_physfiz_timemax", Min = 1, Max = 60, Type = "float" })
        cpanel:AddControl("Checkbox", {Label = "Only disable from player damage?", Command = "sv_physfiz_pvponly" })
        cpanel:AddControl("Checkbox", {Label = "Fizzle blocks prop spawning?", Command = "sv_physfiz_blockprop" })
        cpanel:AddControl("Label", {Text = ""})
        cpanel:AddControl("Checkbox", {Label = "Enable mashing?", Command = "sv_physfiz_unjam" })
        cpanel:AddControl("Slider", {Label = "Time per mash", Command = "sv_physfiz_unjam_amount", Min = 0, Max = 5, Type = "float" })
        cpanel:AddControl("Label", {Text = "If mashing is enabled, pressing mouse buttons or reload will make the fizzle effect go away quicker."})
 
        cpanel:AddControl("Header", {Description = ""})
        cpanel:AddControl("Header", {Description = "Addon created by 8Z"})
    end
	
    hook.Add( "PopulateToolMenu", "PhysgunFizzle", function()
        spawnmenu.AddToolMenuOption( "Options", "Physgun Fizzle", "", "Options", "", "", options)
    end )
end