
squad_menu.title=Меню сквадов
squad_menu.yes=Да
squad_menu.no=Нет
squad_menu.ok=ОК
squad_menu.tab.squad_list=Список сквадов
squad_menu.tab.squad_properties=Настройки сквада
squad_menu.tab.squad_members=Участники сквада
squad_menu.tab.join_requests=Запросы на присоединение
squad_menu.tab.settings=Настройки
squad_menu.create_squad=Создать сквад
squad_menu.edit_squad=Редактировать сквад
squad_menu.leave_squad=Выйти из сквада
squad_menu.leave_leader=Вы лидер сквада. Выход из сквада, расформирует его. Вы уверены?
squad_menu.leave_first=Вы уже состоите в скваде. Покиньте его если хотите присоединится к другим.
squad_menu.leave_first_create=Вы уже состоите в скваде. Покиньте его если хотите создать новый.
squad_menu.join=Зайти
squad_menu.request_to_join=Запрос на вход
squad_menu.waiting_response=Запрос отправлен...
squad_menu.fetching_data=Принимаем данные из внеземных спутников земли...
squad_menu.no_available_squads=Пусто.
squad_menu.not_in_a_squad=Вы не в скваде.
squad_menu.not_squad_leader=Вы не лидер сквада.
squad_menu.slots=Слоты
squad_menu.full_squad=Этот сквад заполнен
squad_menu.member_limit_reached=Этот сквад превысил лимит по участникам.
squad_menu.no_requests_yet=Пусто.
squad_menu.no_requests_needed=Это публичный сквад, никому не нужен запрос на вход.
squad_menu.no_members=Пусто.
squad_menu.requests_list=Эти игроки ожидают вашего решения.
squad_menu.cannot_accept_more=Лимит по участникам сквада превышен! Вы не можете добавить кого либо
squad_menu.accept=Принять
squad_menu.kick=Кикнуть
squad_menu.squad_name=Название сквада
squad_menu.choose_icon=Выбрать иконку...
squad_menu.squad_color=Цвет сквада
squad_menu.squad_is_public=Разрешить кому угодно зайти
squad_menu.squad_friendly_fire=Разрешить дружественный-огонь
squad_menu.squad_rings=Show ring around members
squad_menu.member_joined=%s присоединился к скваду!
squad_menu.member_left=%s ушел из сквада!
squad_menu.squad_welcome=Добро пожаловать в сквад:
squad_menu.squad_created=%s создал сквад:
squad_menu.chat_tip=Введите любую из этих команд, чтобы общаться только со своим отрядом:
squad_menu.request_message=%s хочет присоеденится к вашему скваду.
squad_menu.left_squad=Вы вышли из сквада.
squad_menu.deleted_squad=Ваш сквад был расформирован.
squad_menu.kicked_from_squad=Вы были кикнуты со сквада.
squad_menu.default_squad_name=%s's Сквад
squad_menu.settings.show_members=Показывать список участников на экране
squad_menu.settings.show_halos=Show halos around members
squad_menu.settings.show_rings=Show rings around members
squad_menu.settings.enable_sounds=Play UI sounds
squad_menu.settings.name_draw_distance=Name draw distance
squad_menu.settings.halo_draw_distance=Halo draw distance
squad_menu.settings.ping_key=Пинг